/**
 * TypeDoc plugin to generate llms.txt files for LLM consumption
 *
 * @packageDocumentation
 */

import fs from 'node:fs';
import path from 'node:path';
import { type Application, RendererEvent } from 'typedoc';

import {
  autoGenerateDeclarations,
  discoverSectionsFromProject,
  getProjectDescription,
  getProjectName,
  type LlmsTxtContent,
  renderLlmsTxt,
  resolveDeclarations,
} from './generator.js';
import { declareOptions, getOptions } from './options.js';
import { applyTemplate, readTemplate, templateExists } from './template.js';

export {
  discoverSections,
  discoverSectionsFromProject,
  type DocumentInfo,
  extractFrontmatter,
  type LlmsTxtContent,
  renderLlmsTxt,
  type ResolvedDeclaration,
  type Section,
  stripYamlQuotes,
  titleToUrlPath,
} from './generator.js';
export { declareOptions, getOptions } from './options.js';
export type {
  LlmsTxtDeclaration,
  LlmsTxtHeader,
  LlmsTxtSectionConfig,
} from './options.js';
export { applyTemplate, findSlots, readTemplate } from './template.js';

/**
 * TypeDoc plugin entry point
 *
 * @function
 * @param app - TypeDoc application instance
 */
export const load = (app: Application): void => {
  // Register options
  declareOptions(app);

  // Hook into render end to generate llms.txt
  app.renderer.on(RendererEvent.END, (event) => {
    const options = getOptions(app);

    if (!options.enabled) {
      app.logger.info('[llms-txt] Generation disabled');
      return;
    }

    // Get the router - it should be available at render end
    const router = app.renderer.router;
    if (!router) {
      app.logger.error('[llms-txt] Router not available, cannot generate URLs');
      return;
    }

    const project = event.project;
    const outputDir = app.options.getValue('out') as string;

    // Determine base URL
    const cname = app.options.getValue('cname') as string | undefined;
    const baseUrl = cname ? `https://${cname}` : '';

    // Build content
    const header = {
      description: getProjectDescription(app, options.header),
      features: options.header.features ?? [],
      name: getProjectName(app, options.header),
    };

    // Discover sections from project document reflections (using router for URLs)
    const sections = discoverSectionsFromProject(
      project,
      router,
      options.sections,
      baseUrl,
    );

    // Resolve or auto-generate declarations (using router for URLs)
    let declarations;
    if (options.declarations.length > 0) {
      declarations = resolveDeclarations(
        options.declarations,
        project,
        router,
        app,
        baseUrl,
      );
    } else {
      declarations = autoGenerateDeclarations(project, router, baseUrl);
    }

    const content: LlmsTxtContent = {
      declarations,
      header,
      quickReference: options.quickReference,
      sections,
    };

    // Render content
    let output: string;

    if (options.template && templateExists(options.template)) {
      // Use custom template
      const template = readTemplate(options.template);
      output = applyTemplate(template, content);
      app.logger.info(`[llms-txt] Using template: ${options.template}`);
    } else {
      // Use default rendering
      output = renderLlmsTxt(content);
    }

    // Write to output directory
    const outputPath = path.join(outputDir, options.filename);
    fs.writeFileSync(outputPath, output, 'utf8');
    app.logger.info(
      `[llms-txt] Generated ${path.relative(process.cwd(), outputPath)}`,
    );
  });
};
